---
apiVersion: v1
kind: Namespace
metadata:
   name: monitoring
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kibana-service
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    name: webinterface
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.2.0
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch.monitoring.svc.cluster.local:9200
        ports:
        - containerPort: 5601
          name: webinterface
