apiVersion: v1
kind: Service
metadata:
  name: spring-boot-simple
  labels:
    run: spring-boot-simple
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring-boot-simple
